### ISSUE TITLE
自动部署时候报错

### ISSUE THREAD

**Issue by tkfanswind** [spencerwooo/onedrive-cf-index#128]
Installing wranglerjs v1.14.1...
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- /github/workspace/.cache/.wrangler/wranglerjs-1.14.1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/github/workspace/.cache/.wrangler/wranglerjs-1.14.1/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/github/workspace/.cache/.wrangler/wranglerjs-1.14.1/index.js' ]
}
Error: failed to execute `"/usr/local/bin/node" "/github/workspace/.cache/.wrangler/wranglerjs-1.14.1" "--output-file=/tmp/.wranglerjs_outputHG0MS" "--wasm-binding=WASM_MODULE" "--no-webpack-config=1" "--use-entry=/github/workspace/./src/index.js"`: exited with exit code: 1

**Comment by tkfanswind** [comment]
好像是因为用了wranglerjs-1.14.1，
main内容如下
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}

**Comment by spencerwooo** [comment]
参考 <https://github.com/cloudflare/wrangler-action/issues/50> 解决的，应该是 wrangler 那边的问题。
